name: YamlsucksCD

on:
  workflow_run:
    workflows: ["YamlsucksCI"]
    types:
      - completed

env:
  APP_NAME: "DucksAreReal"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debugging
        run: ls -R

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: publish  # Specify the name of the artifact you uploaded in CI
          path: ./downloaded-artifact  # Specify the path to download the artifact
      
      # Add your deployment steps here
      # For example, deploying to a server or a cloud service
      
      # Example step to list the downloaded artifact
      - name: List downloaded artifact
        run: ls ./downloaded-artifact

      - name: Deploy to web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_KEY }}
          package: ./publish  # This path should be relative to your current working directory
