name: YamlsucksCI

on:
  workflow_dispatch

env:
  APP_NAME: "DucksAreReal"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Install dependencies
        run: dotnet restore ./TestYAML/TestYAML.csproj

      - name: Build project
        run: dotnet build ./TestYAML/TestYAML.csproj -c Release

      - name: Publish project
        run: dotnet publish ./TestYAML/TestYAML.csproj -c Release --output ./publish

      - name: Upload to Azure Storage
        uses: Azure/cli@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob upload-batch --destination workflows --source ./publish --connection-string "BlobEndpoint=https://yamlsuckswilly.blob.core.windows.net/;QueueEndpoint=https://yamlsuckswilly.queue.core.windows.net/;FileEndpoint=https://yamlsuckswilly.file.core.windows.net/;TableEndpoint=https://yamlsuckswilly.table.core.windows.net/;SharedAccessSignature=sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2023-08-30T00:00:28Z&st=2023-08-23T16:00:28Z&spr=https&sig=5qiXkpM7%2B57INO%2FVrl80s85CdXdG45pzYhnQXcGsV1c%3D"
