name: YamlsucksCI

on:
  workflow_dispatch

env:
  APP_NAME: "DucksAreReal"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Install dependencies
        run: dotnet restore ./TestYAML/TestYAML.csproj

      - name: Build project
        run: dotnet build ./TestYAML/TestYAML.csproj -c Release

      - name: Publish project
        run: dotnet publish ./TestYAML/TestYAML.csproj -c Release --output ./publish

      - name: Upload artifact to Azure Storage
        env:
          AZURE_STORAGE_ACCOUNT: yamlsuckswilly
          AZURE_STORAGE_CONTAINER: workflow
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_SA_KEY }}
        run: |
          ARTIFACT_PATH="./publish"
          ARTIFACT_URL="https://${{AZURE_STORAGE_ACCOUNT}}.blob.core.windows.net/${{AZURE_STORAGE_CONTAINER}}/${{ARTIFACT_PATH}}"  # Replace with your blob URL
          echo "Uploading artifact to: $ARTIFACT_URL"
          curl -X PUT -T "$ARTIFACT_PATH" -H "x-ms-blob-type: BlockBlob" "$ARTIFACT_URL?${{SAS_TOKEN}}"