name: Yamlsucks

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .net core
      - uses: actions/setup-dotnet@v1
        with:
        dotnet-version: 7.0.x

        - name: Install dependecies
          run: dotnet restore ./TestYAML/TestYAML.csproj

        - name: Build project
          run: dotnet build ./TestYAML/TestYAML.csproj -configuration release --output ./publish
